name: graph
description: Graph utilities for flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter